title: Laurent Boileau
description: Software developer in Montr√©al, Canada
baseurl:
url: https://laurentboileau.ca

timezone: America/Toronto

author:
  name: Laurent Boileau
  twitter: laurentboileau
  
external_project_links:
  - title: Stations for iPhone
    url: "https://stationsmontreal.app"

social_links:
  - title: GitHub
    url: "https://github.com/laurentboileau"
  - title: Twitter
    url: "https://twitter.com/laurentboileau"

syndication_links:
  - title: RSS
    url: "/feed.xml"

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.markdown"

plugins:
  - jekyll-feed
